import type { Metadata } from "next";
import ContextProvider from '@/context'

import './../styles/styles.scss'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <ContextProvider>
        <body suppressHydrationWarning={true}>
          {children}
        </body>
      </ContextProvider>
    </html>
  );
}
